// <auto-generated />
using System;
using AnalyticsService.DataAccess.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnalyticsService.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260222161342_RemoveIndexForSprintTaskAnalitics")]
    partial class RemoveIndexForSprintTaskAnalitics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalyticsService.Domain.Entities.AnalitycsModels.SprintAnalyticsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SprintId");

                    b.ToTable("SprintAnalytics", (string)null);
                });

            modelBuilder.Entity("AnalyticsService.Domain.Entities.AnalitycsModels.SprintTaskAnalyticsEntity", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("TaskId");

                    b.HasIndex("SprintId");

                    b.ToTable("SprintTaskAnalytics", (string)null);
                });

            modelBuilder.Entity("AnalyticsService.Domain.Entities.InsightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SprintId", "UserId", "Type")
                        .IsUnique();

                    b.ToTable("Insights", (string)null);
                });

            modelBuilder.Entity("AnalyticsService.Domain.Entities.MessageConsumerEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "ConsumerName");

                    b.ToTable("MessageConsumers", (string)null);
                });

            modelBuilder.Entity("AnalyticsService.Domain.Entities.AnalitycsModels.SprintTaskAnalyticsEntity", b =>
                {
                    b.HasOne("AnalyticsService.Domain.Entities.AnalitycsModels.SprintAnalyticsEntity", "Sprint")
                        .WithMany("Tasks")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("AnalyticsService.Domain.Entities.AnalitycsModels.SprintAnalyticsEntity", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
